# Generated by Django 5.2.4 on 2025-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_oficina_nombre_alter_oficina_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre_corto',
            field=models.CharField(help_text='Nombre corto de la oficina (ADM, JAS,MARK, etc)', max_length=10),
        ),
    ]
