# Generated by Django 5.2.4 on 2025-08-21 12:53

import oficina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_alter_oficina_nombre_alter_oficina_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='nombre_corto',
            field=models.CharField(help_text='Nombre corto de la oficina (ADM, JAS,MARK, etc)', max_length=10, unique=True, validators=[oficina.models.Validacion_nombre_corto]),
        ),
    ]
