# Generated by Django 5.2.4 on 2025-08-21 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=18, help_text='Ingrese la edad de la persona.', validators=[django.core.validators.MinValueValidator(18, message='La edad mínima es 18 años.'), django.core.validators.MaxValueValidator(90, message='La edad máxima es 90 años.')], verbose_name='edad'),
            preserve_default=False,
        ),
    ]
